CREATE OR REPLACE FORCE VIEW GG_ADMIN.SKU_INSTANCE AS
SELECT  ERP_INVENTORY_ID,   SKU,   ADD_DATE,   MOD_DATE,   ORG_ID,   UOM_,   SUBINVENTORY_SHORT_CODE,   LOCATOR_ID,   LOCATOR_SHORT_NAME,   SOURCE_TYPE,   TRANSACTION_TYPE,   TRANSACTION_SOURCE,   TRANSACTION_TIME,   LPN_NO,
   SHIPMENT_NO,   TRANSACTION_ACTION,   LOCATION,   SOURCE_PROJECT_NUMBER,   SOURCE_TASK_NUMBER,   PROJECT_NUMBER,
   TASK_NUMBER,   TO_PROJECT_NUMBER,   TO_TASK_NUMBER,   FROM_OWNING_PARTY,   TRANSPORT_COMPANY_ID,   TRANSPORT_COMPANY_NAME,
   NAME_DELIVERY_PERSON,   PLATE_NO,   TRANSPORT_ATT_ID,   MOD_BY,   FORM_ZIP_CODE,   TO_ZIP_CODE,   ORG_DES,   SUBINV_DES,
   LOC_DES,   MOVE_ORDER_LINE_ID,   TRANSACTION_SOURCE_ID,   SHIP_TO_LOCATION_ID,   OC
FROM GG_ADMIN.SKU_INSTANCE_HIST;

