CREATE OR REPLACE FORCE VIEW GG_ADMIN.V_SKU_INSTANCE_TEST AS
SELECT
    mmt."ERP_INVENTORY_ID",mmt."INVENTORY_ITEM_ID",mmt."ADD_DATE",mmt."MOD_DATE",mmt."ORG_ID",mmt."UOM",mmt."SUBINVENTORY_SHORT_CODE",mmt."LOCATOR_ID",mmt."TRANSACTION_SOURCE_TYPE_ID",mmt."TRANSACTION_TYPE_ID",mmt."TRANSACTION_SOURCE",mmt."TRANSACTION_TIME",mmt."SHIPMENT_NO",mmt."TRANSACTION_ACTION",mmt."FROM_OWNING_PARTY",mmt."WAYBILL_AIRBILL",mmt."FREIGHT_CODE",mmt."PICKING_LINE_ID",mmt."ORG_DES",mmt."SUBINV_DES",mmt."LOC_DES"
    ,sid.serial_number 
FROM 
    gg_admin.TEST_MTL_MAT_TX MMT
    LEFT JOIN gg_admin.SKU_INSTANCE_DETAIL sid
        ON mmt.erp_inventory_id=sid.transacton_id;

